#Servicios de almacenamiento de datos


services:
  mongodb:
    image: mongo:latest
    container_name: vivesbank-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: vivesbank
    volumes:
      - ./data:/data/db